// Per-algorithm metadata (drives the dropdown + info panel). Ordered by real-world usage.
const ORDER = [
  "timsort", "quick", "merge", "heap", "insertion",
  "counting", "radix", "bucket",
  "shell", "selection", "bubble", "cocktail", "comb", "gnome",
  "bogo",
];

const META = {
  timsort: {
    name: "Timsort", category: "Hybrid (real-world default)",
    best: "O(n)", avg: "O(n log n)", worst: "O(n log n)", space: "O(n)",
    stable: true, inPlace: false,
    desc: "The go-to general-purpose sort. Detects already-ordered runs, sorts short runs with insertion sort, then merges. It's what Python's sorted()/list.sort() and Java's object sort use.",
    note: "Note: this visualization is a simplified version (insertion + merge). The real Timsort does more.",
    when: "When you just want to sort and not think about it. Real data is often partly ordered, and Timsort exploits that.",
    pros: ["Very fast on real data (approaches O(n) when partly sorted)", "Stable", "Guaranteed O(n log n) worst case"],
    cons: ["Complex to implement", "Needs O(n) extra memory"],
  },
  quick: {
    name: "Quicksort", category: "Comparison · divide & conquer",
    best: "O(n log n)", avg: "O(n log n)", worst: "O(n²)", space: "O(log n)",
    stable: false, inPlace: true,
    desc: "Picks a pivot and partitions into smaller/larger groups, then recurses. Small constant factor makes it fast in practice; it's the core of many standard library sorts.",
    when: "When you want a fast general sort, don't need stability, and want to save memory.",
    pros: ["Fast in practice (small constant factor)", "Almost no extra memory (in-place)"],
    cons: ["O(n²) worst case with bad pivots", "Not stable", "Uses recursion stack"],
  },
  merge: {
    name: "Merge sort", category: "Comparison · divide & conquer",
    best: "O(n log n)", avg: "O(n log n)", worst: "O(n log n)", space: "O(n)",
    stable: true, inPlace: false,
    desc: "Splits the array in half, sorts each half, then merges two sorted runs. Performance is O(n log n) regardless of input.",
    when: "When you need stability, are sorting linked lists, or doing external sorts (data too big for memory).",
    pros: ["Guaranteed O(n log n) worst case", "Stable", "Good for linked lists / external sort"],
    cons: ["Needs O(n) extra memory", "In-place version on arrays is complex"],
  },
  heap: {
    name: "Heap sort", category: "Comparison · selection (heap)",
    best: "O(n log n)", avg: "O(n log n)", worst: "O(n log n)", space: "O(1)",
    stable: false, inPlace: true,
    desc: "Builds a max-heap, then repeatedly extracts the max to the end. Same mechanism as a priority queue.",
    when: "When you want guaranteed O(n log n) with no extra memory.",
    pros: ["Guaranteed O(n log n)", "In-place (O(1) extra memory)"],
    cons: ["Not stable", "Poor cache locality, usually slower than quicksort in practice"],
  },
  insertion: {
    name: "Insertion sort", category: "Comparison · simple",
    best: "O(n)", avg: "O(n²)", worst: "O(n²)", space: "O(1)",
    stable: true, inPlace: true,
    desc: "Inserts each element into its correct spot in the sorted prefix — like sorting a hand of cards.",
    when: "Small arrays, nearly-sorted data, or as the base case inside faster hybrid sorts.",
    pros: ["Very fast on small / nearly-sorted data (best O(n))", "Stable", "Simple, in-place", "Works online (incoming data)"],
    cons: ["O(n²) on large random data"],
  },
  counting: {
    name: "Counting sort", category: "Non-comparison",
    best: "O(n+k)", avg: "O(n+k)", worst: "O(n+k)", space: "O(n+k)",
    stable: true, inPlace: false,
    desc: "Counts occurrences of each value and writes them back from the prefix sums. No comparisons, so it beats the O(n log n) bound.",
    when: "Integer keys in a small range (ages, scores, byte values).",
    pros: ["O(n+k), faster than the comparison lower bound", "Stable"],
    cons: ["Breaks down if the value range k is large", "Integer / discrete keys only"],
  },
  radix: {
    name: "Radix sort (LSD)", category: "Non-comparison",
    best: "O(d·(n+b))", avg: "O(d·(n+b))", worst: "O(d·(n+b))", space: "O(n+b)",
    stable: true, inPlace: false,
    desc: "Sorts digit by digit from least-significant, using a stable sort (e.g. counting) per digit. d = #digits, b = base.",
    when: "Fixed-length integer or string keys (IDs, zip codes, fixed-width strings).",
    pros: ["Strong on large integer-key sets", "Stable"],
    cons: ["Tied to digit count / base, not for general comparisons", "Needs extra memory"],
  },
  bucket: {
    name: "Bucket sort", category: "Non-comparison",
    best: "O(n+k)", avg: "O(n+k)", worst: "O(n²)", space: "O(n+k)",
    stable: true, inPlace: false,
    desc: "Distributes values into buckets by range, sorts each bucket, then concatenates. Buckets stay small when the data is uniform.",
    when: "When data is uniformly distributed over a range (e.g. random values).",
    pros: ["Average O(n+k) for uniform data"],
    cons: ["O(n²) worst case for skewed data", "Needs extra memory"],
  },
  shell: {
    name: "Shell sort", category: "Comparison · insertion-based",
    best: "O(n log n)", avg: "~O(n^1.25)", worst: "O(n²)", space: "O(1)",
    stable: false, inPlace: true,
    desc: "Insertion sort over spaced gaps, shrinking the gap each pass. Resolves distant inversions early.",
    when: "When you want something simple, in-place, and decently fast (e.g. embedded).",
    pros: ["In-place", "Much faster than plain insertion sort", "Relatively simple"],
    cons: ["Complexity depends on the gap sequence (hard to analyze)", "Not stable"],
  },
  selection: {
    name: "Selection sort", category: "Comparison · simple",
    best: "O(n²)", avg: "O(n²)", worst: "O(n²)", space: "O(1)",
    stable: false, inPlace: true,
    desc: "Repeatedly selects the minimum of the unsorted part and places it at the front.",
    when: "When you want to minimize the number of swaps (expensive writes). Mostly educational.",
    pros: ["Minimal swaps (O(n))", "In-place, simple"],
    cons: ["Always O(n²) comparisons (slow regardless of input)", "Not stable"],
  },
  bubble: {
    name: "Bubble sort", category: "Comparison · simple",
    best: "O(n)", avg: "O(n²)", worst: "O(n²)", space: "O(1)",
    stable: true, inPlace: true,
    desc: "Compares adjacent items and swaps if out of order, sweeping repeatedly. Large values 'bubble' to the end.",
    when: "Mostly educational. With early-exit it can detect nearly-sorted input.",
    pros: ["Simplest to implement", "Stable", "Early-exit gives O(n) on nearly-sorted data"],
    cons: ["O(n²) in general — among the slowest in practice"],
  },
  cocktail: {
    name: "Cocktail shaker sort", category: "Comparison · bubble variant",
    best: "O(n)", avg: "O(n²)", worst: "O(n²)", space: "O(1)",
    stable: true, inPlace: true,
    desc: "Bubble sort that sweeps in both directions, sorting from both ends.",
    when: "Educational. A small improvement on bubble sort.",
    pros: ["Sometimes faster than bubble sort", "Stable"],
    cons: ["Still O(n²)"],
  },
  comb: {
    name: "Comb sort", category: "Comparison · bubble variant",
    best: "O(n log n)", avg: "O(n² / 2^p)", worst: "O(n²)", space: "O(1)",
    stable: false, inPlace: true,
    desc: "Bubble sort with a large, shrinking gap. Clears distant inversions ('turtles') quickly.",
    when: "Educational. A practical improvement on bubble sort.",
    pros: ["Much faster than bubble sort", "In-place"],
    cons: ["Not stable", "Still no match for quicksort"],
  },
  gnome: {
    name: "Gnome sort", category: "Comparison · simple",
    best: "O(n)", avg: "O(n²)", worst: "O(n²)", space: "O(1)",
    stable: true, inPlace: true,
    desc: "Like insertion sort but moves back one step whenever it finds an inversion. Extremely simple.",
    when: "Educational / novelty. An example of minimal code.",
    pros: ["Extremely simple", "In-place, stable"],
    cons: ["O(n²), slow"],
  },
  bogo: {
    name: "Bogosort", category: "Joke",
    best: "O(n)", avg: "O(n·n!)", worst: "∞ (may never finish)", space: "O(1)",
    stable: false, inPlace: true,
    desc: "Shuffles the array at random until it happens to be sorted. A joke sort.",
    when: "Never (it's a joke). A fun way to feel how extreme complexity and randomness get.",
    pros: ["Trivially simple"],
    cons: ["Average O(n·n!) — absurdly slow", "No guarantee it ever finishes"],
  },
};

if (typeof module !== "undefined" && module.exports) module.exports = { META, ORDER };
